### ISSUE TITLE
Define communication protocol server <-> client

### ISSUE THREAD

**Issue by 22phuber** [22phuber/tron-light-cycles#29]
We need to define the protocol between server and client:
- client -> server
   - get current games
   - get rounds e.g. when can the client join next round
   - client is ready and client config (preferred color, clientid if exists)
   - create new game with config (mode)
   - leaves game e.g. disconnect
- server -> client
   - send current games
   - send unique clientid (if new game and no client id has been sent from client)
   - confirm new lobby (send game link)
   - send death (collision)
   - send end game or next round
   - send scores
   - send game config (width, height, mode)

... etc.

**Comment by 22phuber** [comment]
Current message from `GameServer`: 
```
{"subject":"canvas config","width":400,"height":400}
{"subject":"canvas config","width":400,"height":400}
{"subject":"player update","players":[]}
{"subject":"player update","players":[]}
{"subject":"player update","players":[{"posx":0,"posy":1,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}
{"subject":"player update","players":[{"posx":0,"posy":2,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}
{"subject":"player update","players":[{"posx":0,"posy":3,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}
{"subject":"player update","players":[{"posx":0,"posy":4,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}
{"subject":"player update","players":[{"posx":0,"posy":5,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}
```

**Comment by 22phuber** [comment]
React client sends `{ subject: "updatePublicGames" }` to gameserver for a public ongoing game list.
Expected Answer ```{
  subject: "currentPublicGames",
  Games: [
    {
      id: "c-47Bs_zTEOZ7-U7TigC7g",
      name: "ZHAWBrainspopper",
      players: "2/3",
      mode: "Tron classic",
    },
    {
      id: "h5diOYzwdESSmWE6yubojQ",
      name: "ShizzleDizzle",
      players: "66/75",
      mode: "Battle Royale",
    }
  ]
}```

**Comment by 22phuber** [comment]
create lobby/game:  `{ subject: "createGame", gameConfig: { name: "somename", visibility: "public", mode: "Battl", "maxplayers":"5/100" } }`
Answer:
```{ subject: "createGame", gameid: "string" }```

**Comment by 22phuber** [comment]
server<->client id: Nach Websocket connection ```{ subject: "clientid", id: "string" }```

**Comment by 22phuber** [comment]
Game starts:

Initial game data from Gameserver: 
`{"subject":"playerUpdatesInitial", gameid: "id" ,"players":[{"posx":0,"posy":5,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}`

Countdown (GS):
 `{"subject":"countdown", count:""}`

Games running: 
Server sends ```{"subject":"playerUpdates", gameid: "id" ,"players":[{"posx":0,"posy":5,"color":"rgb(44,123,246)","id":"f01898fffe12ba85-000152c8-00000001-9b1002a8890b7ab5-be02a89f","dir":1}]}```

Client send direction updates: `{ subject: "updateDirection", key: "key" }`

Death message Broadcast to all clients: ```{ subject: "playerDeath",id:"playerid","posx":0,"posy":5}```

- Player wins & scores (broadcast)
- end game (broadcast)
- lobbyInfos (loop again)

**Comment by cHristianOLI** [comment]
[table with messages](https://github.com/22phuber/tron-light-cycles/blob/develop/documents/client-server-messaging/json_messages.md)
