### ISSUE TITLE
Bedienungsanleitung

### ISSUE THREAD

**Issue by 22phuber** [22phuber/tron-light-cycles#69]
Abgabe Bedienungsanleitung: Als PDF-Datei auf OLAT bis 15.5.2020

Noten und Feedback am 20.5. & Testlauf (for fun!) 

Auf MS-Teams PSIT3

Der Zeitplan wird von Daniel Liebhart kommuniziert. 
Die Teams laden jeweils Johanna Decurtins über MS Teams ein, sobald der Testlauf durchgeführt werden kann.

**Comment by 22phuber** [comment]
Link Video: https://web.microsoftstream.com/video/11cfb2d8-ca56-41b3-a9f0-5c7703c2e4a0

**Comment by mikeiten04** [comment]
bin ich dran
